### ISSUE TITLE
Back of case needs to clear the white debug connector

### ISSUE THREAD

**Issue by allenrowand** [frijoles001/BTT-PITFT5_V2_Mount_Voron2.4#1]
On my board the white connector between the direction switch and reset button was proud of the lip on the front of the case, so the back wasn't flush when mated. I made an edit to the back to make it fit, I'd be happy to share it with you if you'd like.

Thanks for you work!

**Comment by frijoles001** [comment]
Yes please, I can add it to the files as an extra option

**Comment by frijoles001** [comment]
> On my board the white connector between the direction switch and reset button was proud of the lip on the front of the case, so the back wasn't flush when mated. I made an edit to the back to make it fit, I'd be happy to share it with you if you'd like.
> 
> Thanks for you work!

Yes please, I can add it to the files as an extra option

**Comment by allenrowand** [comment]
Here you go:
[PiTFT50 mount edit.stl.zip](https://github.com/frijoles001/BTT-PITFT5_V2_Mount_Voron2.4/files/8792611/PiTFT50.mount.edit.stl.zip)

**Comment by frijoles001** [comment]
> Here you go: [PiTFT50 mount edit.stl.zip](https://github.com/frijoles001/BTT-PITFT5_V2_Mount_Voron2.4/files/8792611/PiTFT50.mount.edit.stl.zip)

Thanks!  just uploaded it and added description to the readme
